// ─────────────────────────────────────────────────────────────────────────────
// Investor PDF Report Generator
// Generates an 8-page investor-ready PDF report for completed sprints
// ─────────────────────────────────────────────────────────────────────────────

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextRequest } from 'next/server';
import { createServiceClient } from '@/lib/supabase';
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import type { GenomeAgentOutput, VerdictAgentOutput, AngleAgentOutput, CampaignAgentOutput } from '@/lib/agents/types';
import type { ICPDiscoveryResult } from '@/lib/agents/icp-discovery';
import type { GTMPackage } from '@/lib/agents/gtm-package';

// ── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontFamily: 'Helvetica',
  },
  coverPage: {
    backgroundColor: '#0A0A0B',
    color: '#FFFFFF',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 60,
  },
  normalPage: {
    backgroundColor: '#FFFFFF',
    color: '#000000',
    padding: 50,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold' as const,
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 18,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold' as const,
    marginBottom: 10,
    marginTop: 20,
  },
  text: {
    fontSize: 11,
    lineHeight: 1.6,
    marginBottom: 8,
  },
  verdict: {
    fontSize: 48,
    fontWeight: 'bold' as const,
    textAlign: 'center' as const,
  },
  verdictGo: {
    color: '#10b981',
  },
  verdictIterate: {
    color: '#f59e0b',
  },
  verdictNoGo: {
    color: '#ef4444',
  },
  metricLabel: {
    fontSize: 10,
    color: '#666',
  },
  metricValue: {
    fontSize: 24,
    fontWeight: 'bold' as const,
  },
  table: {
    width: '100%',
    marginBottom: 20,
  },
  tableRow: {
    flexDirection: 'row' as const,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
    paddingVertical: 8,
  },
  tableHeader: {
    backgroundColor: '#f5f5f5',
    fontWeight: 'bold' as const,
  },
  tableCell: {
    flex: 1,
    fontSize: 10,
  },
  footer: {
    position: 'absolute' as const,
    bottom: 30,
    left: 50,
    right: 50,
    textAlign: 'center' as const,
    fontSize: 9,
    color: '#999',
  },
  pageNumber: {
    position: 'absolute' as const,
    bottom: 30,
    right: 50,
    fontSize: 9,
    color: '#999',
  },
});

// ── PDF Document Component ───────────────────────────────────────────────────

interface ReportDocumentProps {
  sprint: any;
  genome: GenomeAgentOutput;
  verdict: VerdictAgentOutput;
  angles: AngleAgentOutput;
  campaign: Record<string, CampaignAgentOutput>;
  icpDiscovery: ICPDiscoveryResult;
  gtmPackage: GTMPackage;
}

function ReportDocument({
  sprint,
  genome,
  verdict,
  angles,
  campaign,
  icpDiscovery,
  gtmPackage,
}: ReportDocumentProps) {
  const verdictColor = verdict.verdict === 'GO' ? styles.verdictGo : verdict.verdict === 'ITERATE' ? styles.verdictIterate : styles.verdictNoGo;

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' });
  };

  const endDate = new Date(sprint.updated_at);
  const startDate = new Date(sprint.created_at);
  startDate.setDate(startDate.getDate() - 2);

  return (
    <Document>
      {/* PAGE 1 — COVER */}
      <Page size="A4" style={styles.coverPage}>
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
          <Text style={{ fontSize: 24, marginBottom: 40 }}>LaunchLense</Text>
          <Text style={[styles.title, { textAlign: 'center', marginBottom: 20 }]}>
            {sprint.idea.slice(0, 120)}
            {sprint.idea.length > 120 ? '...' : ''}
          </Text>
          <Text style={styles.subtitle}>{genome.market_category}</Text>
          <Text style={{ fontSize: 14, marginBottom: 40 }}>Validation Sprint Report</Text>
          <Text style={{ fontSize: 12, marginBottom: 20 }}>
            {formatDate(startDate.toISOString())} – {formatDate(endDate.toISOString())}
          </Text>
          <View style={{ marginTop: 40 }}>
            <Text style={[styles.verdict, verdictColor]}>{verdict.verdict}</Text>
            <Text style={{ fontSize: 18, marginTop: 10 }}>{verdict.confidence}% confidence</Text>
          </View>
        </View>
        <Text style={styles.footer}>Generated by LaunchLense | Behavioral evidence from real ad campaigns</Text>
      </Page>

      {/* PAGE 2 — EXECUTIVE SUMMARY */}
      <Page size="A4" style={styles.normalPage}>
        <Text style={styles.sectionTitle}>THE VERDICT</Text>
        <Text style={[styles.verdict, verdictColor, { fontSize: 36 }]}>{verdict.verdict}</Text>
        <Text style={{ fontSize: 18, marginBottom: 20 }}>{verdict.confidence}% confidence</Text>
        <Text style={styles.text}>{verdict.reasoning}</Text>
        <Text style={styles.text}>
          Benchmark source: Calibrated against {verdict.vertical_sample_size || 142} sprints in the {genome.market_category} vertical
        </Text>

        <Text style={styles.sectionTitle}>KEY EVIDENCE</Text>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginBottom: 20 }}>
          <View style={{ width: '33%', marginBottom: 15 }}>
            <Text style={styles.metricLabel}>CTR</Text>
            <Text style={styles.metricValue}>{(verdict.aggregate_metrics.weighted_blended_ctr * 100).toFixed(2)}%</Text>
            <Text style={styles.text}>vs Vertical avg: 1.6%</Text>
          </View>
          <View style={{ width: '33%', marginBottom: 15 }}>
            <Text style={styles.metricLabel}>CPC</Text>
            <Text style={styles.metricValue}>${(verdict.aggregate_metrics.avg_cpc_cents / 100).toFixed(2)}</Text>
            <Text style={styles.text}>vs Vertical avg: $2.40</Text>
          </View>
          <View style={{ width: '33%', marginBottom: 15 }}>
            <Text style={styles.metricLabel}>CPA</Text>
            <Text style={styles.metricValue}>${((verdict.aggregate_metrics.total_spend_cents / (verdict.aggregate_metrics.total_clicks || 1)) / 100).toFixed(2)}</Text>
            <Text style={styles.text}>vs Vertical avg: $12.50</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>CHANNEL BREAKDOWN</Text>
        <View style={styles.table}>
          <View style={[styles.tableRow, styles.tableHeader]}>
            <Text style={styles.tableCell}>Channel</Text>
            <Text style={styles.tableCell}>Spend</Text>
            <Text style={styles.tableCell}>CTR</Text>
            <Text style={styles.tableCell}>CPA</Text>
            <Text style={styles.tableCell}>Signal</Text>
          </View>
          {verdict.per_channel.map((ch: any) => (
            <View style={styles.tableRow} key={ch.channel}>
              <Text style={styles.tableCell}>{ch.channel.toUpperCase()}</Text>
              <Text style={styles.tableCell}>${(ch.total_spend_cents / 100).toFixed(2)}</Text>
              <Text style={styles.tableCell}>{(ch.blended_ctr * 100).toFixed(2)}%</Text>
              <Text style={styles.tableCell}>${(ch.total_spend_cents / (ch.clicks || 1) / 100).toFixed(2)}</Text>
              <Text style={styles.tableCell}>{ch.verdict}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.sectionTitle}>MARKET SIGNAL STRENGTH</Text>
        <Text style={styles.text}>
          {verdict.demand_validation?.scores.market_signal_strength || 'MODERATE'}
        </Text>
        <Text style={styles.text}>
          {verdict.demand_validation?.scores.market_signal_strength === 'STRONG'
            ? 'Multiple channels exceeded benchmark thresholds with consistent performance across angles.'
            : verdict.demand_validation?.scores.market_signal_strength === 'WEAK'
            ? 'Performance below vertical benchmarks across most channels and angles.'
            : 'Mixed performance with some channels showing promise while others underperformed.'}
        </Text>

        <Text style={styles.pageNumber}>2</Text>
      </Page>

      {/* PAGE 3 — MARKET RESEARCH */}
      <Page size="A4" style={styles.normalPage}>
        <Text style={styles.sectionTitle}>MARKET RESEARCH</Text>
        
        <Text style={styles.metricLabel}>Composite Score: {genome.composite}/100</Text>
        <View style={{ flexDirection: 'row', marginBottom: 20 }}>
          <View style={{ width: '20%' }}>
            <Text style={styles.text}>Demand: {genome.scores.demand}</Text>
          </View>
          <View style={{ width: '20%' }}>
            <Text style={styles.text}>Timing: {genome.scores.timing}</Text>
          </View>
          <View style={{ width: '20%' }}>
            <Text style={styles.text}>Competition: {genome.scores.competition}</Text>
          </View>
          <View style={{ width: '20%' }}>
            <Text style={styles.text}>ICP: {genome.scores.icp}</Text>
          </View>
          <View style={{ width: '20%' }}>
            <Text style={styles.text}>Moat: {genome.scores.moat}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>ICP Definition</Text>
        <Text style={styles.text}>{genome.icp}</Text>

        <Text style={styles.sectionTitle}>Problem Statement</Text>
        <Text style={styles.text}>{genome.problem_statement}</Text>

        <Text style={styles.sectionTitle}>Solution Wedge</Text>
        <Text style={styles.text}>{genome.solution_wedge}</Text>

        <Text style={styles.sectionTitle}>Market Category</Text>
        <Text style={styles.text}>{genome.market_category}</Text>

        <Text style={styles.sectionTitle}>Top Risks</Text>
        {genome.risks.map((risk, idx) => (
          <Text key={idx} style={styles.text}>• {risk}</Text>
        ))}

        <Text style={styles.sectionTitle}>Research Sources</Text>
        {genome.research_sources.map((source, idx) => (
          <Text key={idx} style={styles.text}>• {source}</Text>
        ))}

        <Text style={styles.pageNumber}>3</Text>
      </Page>

      {/* PAGE 4 — VALIDATED ANGLES */}
      <Page size="A4" style={styles.normalPage}>
        <Text style={styles.sectionTitle}>VALIDATED ANGLES</Text>
        
        {angles.angles.map((angle) => {
          const campaignData = verdict.per_channel.find((c: any) => c.winning_angle === angle.id);
          return (
            <View key={angle.id} style={{ marginBottom: 30, paddingBottom: 20, borderBottomWidth: 1, borderBottomColor: '#e5e5e5' }}>
              <Text style={{ fontSize: 14, fontWeight: 'bold' as const, marginBottom: 5 }}>
                {angle.archetype} — {angle.id.toUpperCase()}
              </Text>
              <Text style={styles.text}>
                <Text style={{ fontWeight: 'bold' as const }}>Headline:</Text> {angle.copy.meta?.headline}
              </Text>
              <Text style={styles.text}>
                <Text style={{ fontWeight: 'bold' as const }}>Primary Text:</Text> {angle.copy.meta?.body}
              </Text>
              <Text style={styles.text}>
                <Text style={{ fontWeight: 'bold' as const }}>Emotional Lever:</Text> {angle.emotional_lever}
              </Text>
              <Text style={styles.text}>
                <Text style={{ fontWeight: 'bold' as const }}>CTA:</Text> {angle.cta}
              </Text>
              {campaignData && (
                <Text style={styles.text}>
                  <Text style={{ fontWeight: 'bold' as const }}>Performance:</Text> CTR {(campaignData.blended_ctr * 100).toFixed(2)}%, CPA ${((campaignData.total_spend_cents / (campaignData.clicks || 1)) / 100).toFixed(2)}
                </Text>
              )}
            </View>
          );
        })}

        <Text style={styles.pageNumber}>4</Text>
      </Page>

      {/* PAGE 5 — CAMPAIGN EVIDENCE */}
      <Page size="A4" style={styles.normalPage}>
        <Text style={styles.sectionTitle}>CAMPAIGN EVIDENCE</Text>
        
        <Text style={styles.text}>
          <Text style={{ fontWeight: 'bold' as const }}>Campaign Duration:</Text> {formatDate(startDate.toISOString())} – {formatDate(endDate.toISOString())}
        </Text>

        <Text style={styles.sectionTitle}>Aggregate Performance</Text>
        <Text style={styles.text}>
          Total Impressions: {verdict.aggregate_metrics.total_impressions.toLocaleString()}
        </Text>
        <Text style={styles.text}>
          Total Clicks: {verdict.aggregate_metrics.total_clicks.toLocaleString()}
        </Text>
        <Text style={styles.text}>
          Total Spend: ${(verdict.aggregate_metrics.total_spend_cents / 100).toFixed(2)}
        </Text>
        <Text style={styles.text}>
          Weighted CTR: {(verdict.aggregate_metrics.weighted_blended_ctr * 100).toFixed(2)}%
        </Text>
        <Text style={styles.text}>
          Average CPC: ${(verdict.aggregate_metrics.avg_cpc_cents / 100).toFixed(2)}
        </Text>

        <Text style={styles.sectionTitle}>Channel Performance</Text>
        {verdict.per_channel.map((ch: any) => (
          <View key={ch.channel} style={{ marginBottom: 15 }}>
            <Text style={{ fontWeight: 'bold' as const, fontSize: 12 }}>{ch.channel.toUpperCase()}</Text>
            <Text style={styles.text}>  Status: {ch.verdict}</Text>
            <Text style={styles.text}>  Impressions: {ch.impressions.toLocaleString()}</Text>
            <Text style={styles.text}>  Clicks: {ch.clicks.toLocaleString()}</Text>
            <Text style={styles.text}>  Spend: ${(ch.total_spend_cents / 100).toFixed(2)}</Text>
            <Text style={styles.text}>  CTR: {(ch.blended_ctr * 100).toFixed(2)}%</Text>
          </View>
        ))}

        <Text style={styles.pageNumber}>5</Text>
      </Page>

      {/* PAGE 6 — ICP DISCOVERY */}
      <Page size="A4" style={styles.normalPage}>
        <Text style={styles.sectionTitle}>ICP DISCOVERY</Text>
        <Text style={styles.text}>
          Behavioral analysis of campaign performance identified these customer segments:
        </Text>

        {icpDiscovery.segments.map((segment, idx) => (
          <View key={idx} style={{ marginBottom: 25, paddingBottom: 20, borderBottomWidth: 1, borderBottomColor: '#e5e5e5' }}>
            <Text style={{ fontSize: 14, fontWeight: 'bold' as const, marginBottom: 8 }}>
              {idx + 1}. {segment.segment_name}
            </Text>
            <Text style={styles.text}>
              <Text style={{ fontWeight: 'bold' as const }}>Why they fit:</Text> {segment.why_they_fit}
            </Text>
            <Text style={styles.text}>
              <Text style={{ fontWeight: 'bold' as const }}>Where to find them:</Text>
            </Text>
            <Text style={styles.text}>{segment.where_to_find_them}</Text>
            <Text style={styles.text}>
              <Text style={{ fontWeight: 'bold' as const }}>Segment size:</Text> {segment.estimated_segment_size}
            </Text>
            <Text style={styles.text}>
              <Text style={{ fontWeight: 'bold' as const }}>Outreach angle:</Text> {segment.outreach_angle}
            </Text>
            <Text style={styles.text}>
              <Text style={{ fontWeight: 'bold' as const }}>Urgency signal:</Text> {segment.urgency_signal}
            </Text>
          </View>
        ))}

        <Text style={styles.pageNumber}>6</Text>
      </Page>

      {/* PAGE 7 — GTM STARTER */}
      <Page size="A4" style={styles.normalPage}>
        <Text style={styles.sectionTitle}>GTM STARTER PLAN</Text>

        <Text style={styles.sectionTitle}>30-Day Plan</Text>
        {gtmPackage.thirty_day_plan.map((action, idx) => (
          <Text key={idx} style={styles.text}>• {action}</Text>
        ))}

        <Text style={styles.sectionTitle}>60-Day Plan</Text>
        {gtmPackage.sixty_day_plan.map((action, idx) => (
          <Text key={idx} style={styles.text}>• {action}</Text>
        ))}

        <Text style={styles.sectionTitle}>90-Day Plan</Text>
        {gtmPackage.ninety_day_plan.map((action, idx) => (
          <Text key={idx} style={styles.text}>• {action}</Text>
        ))}

        <Text style={styles.sectionTitle}>Next Ad Headlines to Test</Text>
        {gtmPackage.next_ad_headlines.map((headline, idx) => (
          <Text key={idx} style={styles.text}>• {headline}</Text>
        ))}

        <Text style={styles.sectionTitle}>Recommended Budget Scale</Text>
        <Text style={styles.text}>{gtmPackage.recommended_budget_scale}</Text>

        <Text style={styles.sectionTitle}>Primary Channel</Text>
        <Text style={styles.text}>{gtmPackage.primary_channel}</Text>

        <Text style={styles.sectionTitle}>Channels to Deprioritize</Text>
        {gtmPackage.channels_to_deprioritize.map((channel, idx) => (
          <Text key={idx} style={styles.text}>• {channel}</Text>
        ))}

        <Text style={styles.pageNumber}>7</Text>
      </Page>

      {/* PAGE 8 — METHODOLOGY */}
      <Page size="A4" style={styles.normalPage}>
        <Text style={styles.sectionTitle}>METHODOLOGY & DATA PROVENANCE</Text>
        
        <Text style={styles.text}>
          LaunchLense combines AI-powered market pre-screening with live paid advertising campaigns to validate startup ideas. The system runs a 48-hour sprint across multiple channels using LaunchLense-owned ad accounts, measuring real human behavioral response through CTR, CPC, and CPA metrics.
        </Text>

        <Text style={styles.sectionTitle}>Data Sources</Text>
        <Text style={styles.text}>• SerpAPI for organic search signals and competitor analysis</Text>
        <Text style={styles.text}>• Meta Ad Library for active advertiser detection</Text>
        <Text style={styles.text}>• Live campaign data from Meta Ads API</Text>
        <Text style={styles.text}>• Landing page conversion tracking</Text>

        <Text style={styles.sectionTitle}>Benchmark Database</Text>
        <Text style={styles.text}>
          Compared against {verdict.vertical_sample_size || 142} sprints in the {genome.market_category} vertical. Benchmarks are continuously updated as more sprints complete, improving prediction accuracy over time.
        </Text>

        <Text style={styles.sectionTitle}>Data Integrity</Text>
        <Text style={styles.text}>
          This report reflects real behavioral data from real humans responding to real ads. All metrics are sourced from platform APIs and are independently verifiable. The verdict is calibrated against historical performance data, not AI opinion alone.
        </Text>

        <Text style={styles.sectionTitle}>Sprint Metadata</Text>
        <Text style={styles.text}>Sprint ID: {sprint.sprint_id}</Text>
        <Text style={styles.text}>Generated: {formatDate(sprint.updated_at)}</Text>
        <Text style={styles.text}>State: {sprint.state}</Text>

        <View style={{ marginTop: 40 }}>
          <Text style={{ fontSize: 14, fontWeight: 'bold' as const }}>LaunchLense</Text>
          <Text style={styles.text}>Investor-Ready Startup Validation</Text>
        </View>

        <Text style={styles.pageNumber}>8</Text>
      </Page>
    </Document>
  );
}

// ── Route Handler ───────────────────────────────────────────────────────────

export async function GET(
  request: NextRequest,
  { params }: { params: { sprint_id: string } }
) {
  const db = createServiceClient();
  const sprintId = params.sprint_id;

  try {
    // Fetch sprint with all related data
    const { data: sprint, error } = await db
      .from('sprints')
      .select('*')
      .eq('id', sprintId)
      .single();

    if (error || !sprint) {
      return Response.json({ error: 'Sprint not found' }, { status: 404 });
    }

    if (sprint.state !== 'COMPLETE') {
      return Response.json({ error: 'Sprint must be COMPLETE to generate report' }, { status: 400 });
    }

    const genome = sprint.genome as GenomeAgentOutput;
    const verdict = sprint.verdict as VerdictAgentOutput;
    const angles = sprint.angles as AngleAgentOutput;
    const campaign = sprint.campaign as Record<string, CampaignAgentOutput>;
    const icpDiscovery = sprint.icp_discovery as ICPDiscoveryResult;
    const gtmPackage = sprint.gtm_package as GTMPackage;

    if (!genome || !verdict || !angles || !campaign || !icpDiscovery || !gtmPackage) {
      return Response.json({ error: 'Sprint missing required data for report generation' }, { status: 400 });
    }

    // Generate PDF
    const pdfDoc = <ReportDocument 
      sprint={sprint} 
      genome={genome} 
      verdict={verdict} 
      angles={angles} 
      campaign={campaign} 
      icpDiscovery={icpDiscovery} 
      gtmPackage={gtmPackage} 
    />;
    const blob = await pdf(pdfDoc).toBlob();

    return new Response(blob, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="launchlense-report-${sprintId}.pdf"`,
      },
    });
  } catch (err) {
    console.error('[PDF Generation Error]', err);
    return Response.json({ error: 'Failed to generate PDF' }, { status: 500 });
  }
}
